---
title: "Analysis of Abeta-expressing Drosophila in LD"
author: "Yizhou Yu"
date: "28/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load libraries
```{r}
library("behavr")
library("damr")
library("ggetho")
library(sleepr)
library(survival)
library(survminer)
```

Load data into a behavr structure, simultaneously applying the sleep_dam_annotation function

```{r}
DATA_DIR <- "data/"
list.files(DATA_DIR, pattern= "*.txt")
metadata <- fread("data/metadt.csv")
metadata$start_datetime = "2020-07-07 08:00:00"
metadata$stop_datetime = "2020-08-01 08:00:00"
metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR)
dt <- load_dam(metadata, FUN = sleepr::sleep_dam_annotation)
summary(dt)

```



curate dead flies -- this is a big function
default = 1 day inactivity --> dead 
```{r}
dt_curated <- curate_dead_animals(dt)
summary(dt_curated)
```

## Sleep
```{r}
dt_curated[, phase := ifelse(t %% hours(24) < hours(12), "L", "D")]
summary_dt <- 
  rejoin(dt_curated[,
           .(
             # this is where the computation happens
             sleep_fraction_all = mean(asleep),
             sleep_fraction_l = mean(asleep[phase == "L"]),
             sleep_fraction_d = mean(asleep[phase == "D"])
             ),
           ,by=id])

summary_dt_melted <- melt(summary_dt, measure.vars = patterns("sleep_fraction_"),
                          variable.name = "phase", value.name = "sleep_fraction")
summary_dt_melted = subset(summary_dt_melted, genotype == "elavG4_UASAbArc" | genotype == "elavG4_UASAbArc_parpCH1")
ggplot(summary_dt_melted, aes(x=genotype, y=sleep_fraction, fill=genotype)) + 
  geom_boxplot(outlier.colour = NA) +
  #geom_jitter(alpha=.1) +
  theme_classic()+ theme(legend.position = "none", text = element_text(size=15), axis.text.x = 
                           element_text(angle=45, hjust=1))+
  facet_grid(.~phase)+ xlab("")+
  scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)
```

```{r}
summary_dt_melted$geno_phase = paste(summary_dt_melted$genotype, summary_dt_melted$phase, sep = "_")

pairwise.t.test(summary_dt_melted$sleep_fraction, summary_dt_melted$geno_phase, p.adj = "none")

```



## Lifespan
```{r}
# we make a summary table of all lifespan for each animals
lifespan_dt <- dt_curated[, .(lifespan = max(t)), by=id]
head(lifespan_dt)
```


```{r}
lifespan_dt_merged = merge(metadata, lifespan_dt, by = "id")
lifespan_dt_km = lifespan_dt_merged
lifespan_dt_km$total_assay_time = as.numeric(as.POSIXct(lifespan_dt_km$stop_datetime,format='%Y-%m-%d %H:%M:%S') - as.POSIXct(lifespan_dt_km$start_datetime,format='%Y-%m-%d %H:%M:%S'))
lifespan_dt_km$death = NA

for (row in 1:nrow(lifespan_dt_km)){
  if ((lifespan_dt_km$lifespan[row])/86400 >= lifespan_dt_km$total_assay_time[row]) {
    lifespan_dt_km$death[row] = 0
  }
  else {
    lifespan_dt_km$death[row] = 1
  }
}
```

```{r}
lifespan_dt_km_test = subset(lifespan_dt_km, genotype != "elavG4_51D")
lifespan_dt_km_test = subset(lifespan_dt_km_test, genotype != "elavG4_AbArc_RelE20")
lifespan_dt_km_test = subset(lifespan_dt_km_test, genotype != "elavG4_AbArc_dNK")

km_fit = survfit(Surv(lifespan/86400, death) ~ genotype, data = lifespan_dt_km_test)

ggsurv = ggsurvplot(
    fit = km_fit, 
    xlab = "Days", 
    ylab = "Overall survival probability",
    conf.int = TRUE,
    pval = T,
    pval.method = TRUE,
    log.rank.weights = "1")
ggsurv$plot + scale_y_continuous(labels = scales::percent)

ggsave("fig_out/parp_KM_lifespan_graph.pdf", width = 5, height = 3)
```

```{r}
survdiff(Surv(lifespan/86400, death) ~ genotype, data = lifespan_dt_km_test)
wilcox.test(lifespan_dt_km_test$lifespan~lifespan_dt_km_test$genotype)
```


